# Generated by Django 5.1.6 on 2025-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('stock_quantity', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=20),
        ),
    ]
